### ISSUE TITLE
Kiritilgan qiymatni tekshirishda xatolik

### ISSUE THREAD

**Issue by udilbar** [abdulatifkhan/valyuta#1]
![Screenshot_8](https://user-images.githubusercontent.com/68459485/98665659-ca74ed00-236d-11eb-9482-9274673a8494.png)
Inputga string turidagi ma'lumot kiritilganida, NaN ning oldini olishimiz kerak )

**Comment by abdulatifkhan** [comment]
Muammoni bartaraf etdik, e'tibor uchun rahmat!

![image](https://user-images.githubusercontent.com/68887519/98773592-1164f000-240b-11eb-8a6a-c1ffb74b59a8.png)
